### ISSUE TITLE
The crew no longer compatible with kodi version 19.0

### ISSUE THREAD

**Issue by hogscraper** [team-crew/team-crew.github.io#39]
Just got an update for kodi to version 19.0 and it's telling me this version is in compatible so the addon is disabled. 
Edited: using version 0.3.1 of The Crew
Wasn't sure where to report this issue.

**Comment by char543** [comment]
Hey, same issue. Not sure if this helps but im using Kodi 19.0.0 on Darwin 19.6.0. Heres some output from the log:

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "/Users/xxxxxxxx/Library/Application Support/Kodi/addons/repository.thecrew/service.py", line 17, in <module>
                                                       derka = 'Xc3BlY2lhbDovL2hvbWUvYWRkb25zL3BsdWdpbi5wcm9ncmFtLmluZGlnbw=='[1:].decode('base64')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--

**Comment by fade2gray** [comment]
@hogscraper & @char543 see issue #37

**Comment by hogscraper** [comment]
Since this is still an issue and the others relating to this have been closed should I leave this open? People say in other to not update but I didn't have a choice in the matter. Auto update was turned off in the play store and it seems like the app itself turned it's auto update back on so I assume people are going to continue seeing this issue. Going to try to go back to version Kodi 18 if I can.

**Comment by fade2gray** [comment]
May as well - the devs don't visit here too frequently, so it may serve as a warning to others.

**Comment by hogscraper** [comment]
Weird, it says I closed the issue but wasn't even awake 10 hours ago when it said I did so...

**Comment by Tw3ak** [comment]
According to Cody developers these guys knew over a year ago that their add-on was going to be broken with Cody 19 it wasn't a secret they're all just too lazy to update it because they don't want to have to update two different add-ons one for people that keep using the old version of Cody and then them have to make a new one for the new version. The reason it's broke is the old add-ons used python and the new Kodi is using python 3 and nobody wants to have to have two different versions of their add-on for it to work on the old and the new so they're refusing to update it so don't hold your breath that the crew were going to update it now after it's released when they knew a year ago and could have prepared for it and already had it updated.

**Comment by G-streamer** [comment]
Wow, you guys can get hostile. Yes, the python issue has been known for a long time but until the full release of Kodi, most developers didn't want to take the chance of changing their add-on only to have Kodi break it again. It involves more than just changing from python 2 to python 3. There are other changes that need to be put in place. The code also has to be rewritten due to changes in the TVDB api system. IF Team Crew decides to release a Matrix version, they have a lot of work to do. Work that is offered for FREE. Calling them "lazy" is looking a gift horse in the mouth. If it's so easy then use up all your free time to make your own add-on.
