### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by joe71101** [team-crew/team-crew.github.io#68]
So, recent issue, as of yesterday 9/12/21, the addon has stopped working.  When I go to open the addon it says the crew error, check log for information.

**Comment by thebetauser** [comment]
Post the log, I'm using the crew right now without issues

**Comment by michael-j-oconnor** [comment]
My "The Crew" install stopped working at the same time.  
I'm running Kodi 18 on an old Fire TV stick.  
Here's the error log:

```2021-09-20 05:21:06.556 T:8220   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named simplejson
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.thecrew/thecrew.py", line 82, in <module>
                                                from resources.lib.indexers import navigator
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.thecrew/lib/resources/lib/indexers/navigator.py", line 35, in <module>
                                                from resources.lib.modules import trakt
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.thecrew/lib/resources/lib/modules/trakt.py", line 33, in <module>
                                                from resources.lib.modules import client
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.thecrew/lib/resources/lib/modules/client.py", line 11, in <module>
                                                eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
                                              File "<string>", line 28, in <module>
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.thecrew/lib/resources/lib/modules/utils.py", line 26, in <module>
                                                import simplejson as json
                                            ImportError: No module named simplejson
                                            -->End of Python script error report<--
2021-09-20 05:21:06.792 T:8219   ERROR: GetDirectory - Error getting plugin://plugin.video.thecrew/
2021-09-20 05:21:06.894 T:7765   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.thecrew/) failed```

**Comment by Goldie247** [comment]
I get the same error the crew addon will not open and the same error message simplejson not installed was working fine and then just stoped un installed reinstalled but no change any one got a fix for this running 18.9 leia

**Comment by joe71101** [comment]
It's crazy because the crew and tempest were by far the best addons, and now both seem to have gone defunct

**Comment by Goldie247** [comment]
I know right i gave up on tempest a long time ago but the crew was working fine no problems at all now it just will not open due to this i cant even get into the tools menu of the addon so that option is also out i moved to midian and that was great but now for some reason crashes the kodi as soon as i try to exit the addon i have to use task manager to close kodi then restart 

Sent from Yahoo Mail on Android 
 
  On Thu, 30 Sep 2021 at 1:45, ***@***.***> wrote:   


It's crazy because the crew and tempest were by far the best addons, and now both seem to have gone defunct

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by joe71101** [comment]
If you have real debris, venom is really nice.  If not Taz and Alvin in the octopus repo are nice for TV shows and movies, and apex sports has ustvgo, and diamond repo has the loonatics live TV addons. They have tvtap, swift streams, streamline, and ustvgo

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 29, 2021 at 9:16 PM, ***@***.***> wrote:   

I know right i gave up on tempest a long time ago but the crew was working fine no problems at all now it just will not open due to this i cant even get into the tools menu of the addon so that option is also out i moved to midian and that was great but now for some reason crashes the kodi as soon as i try to exit the addon i have to use task manager to close kodi then restart 

Sent from Yahoo Mail on Android 
 
 On Thu, 30 Sep 2021 at 1:45, ***@***.***> wrote: 


It's crazy because the crew and tempest were by far the best addons, and now both seem to have gone defunct

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Goldie247** [comment]
Thanks i have venom as i use the nolimits build i have loonatics but will try taz and alvin but to be honest oath has been doing ok for me and leviathan as a back up between the two i find most if not all i search for 

Sent from Yahoo Mail on Android 
 
  On Thu, 30 Sep 2021 at 3:39, ***@***.***> wrote:   

If you have real debris, venom is really nice.  If not Taz and Alvin in the octopus repo are nice for TV shows and movies, and apex sports has ustvgo, and diamond repo has the loonatics live TV addons. They have tvtap, swift streams, streamline, and ustvgo

Sent from Yahoo Mail on Android 
 
 On Wed, Sep 29, 2021 at 9:16 PM, ***@***.***> wrote: 

I know right i gave up on tempest a long time ago but the crew was working fine no problems at all now it just will not open due to this i cant even get into the tools menu of the addon so that option is also out i moved to midian and that was great but now for some reason crashes the kodi as soon as i try to exit the addon i have to use task manager to close kodi then restart 

Sent from Yahoo Mail on Android 
 
 On Thu, 30 Sep 2021 at 1:45, ***@***.***> wrote: 


It's crazy because the crew and tempest were by far the best addons, and now both seem to have gone defunct

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
 

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thecrewwh** [comment]
There is a import that shouldnt be there is the 18 or 19
